"""empty message

Revision ID: 30325487365f
Revises: 2eed58b56f92
Create Date: 2025-11-24 01:20:23.075498

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '30325487365f'
down_revision = '2eed58b56f92'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finish', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gr_wincon', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('eliminated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_game_result_eliminated_by_id_player',
            'player',
            ['eliminated_by_id'],
            ['id']
        )
        batch_op.drop_column('place')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_game_result_eliminated_by_id_player', type_='foreignkey')
        batch_op.drop_column('eliminated_by_id')
        batch_op.drop_column('gr_wincon')
        batch_op.drop_column('finish')
    # ### end Alembic commands ###
