"""empty message

Revision ID: 5a953fbe218a
Revises: 
Create Date: 2025-11-24 00:10:52.406900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a953fbe218a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_identity',
    sa.Column('code', sa.String(length=1), nullable=False),
    sa.Column('identity_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_player_name'), ['player_name'], unique=True)

    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_name', sa.String(length=100), nullable=False),
    sa.Column('color_identity_code', sa.String(length=1), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color_identity_code'], ['color_identity.code'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('game_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gr_session_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('place', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.ForeignKeyConstraint(['gr_session_id'], ['game_session.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_result_deck_id'), ['deck_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_result_gr_session_id'), ['gr_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_result_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_result_player_id'))
        batch_op.drop_index(batch_op.f('ix_game_result_gr_session_id'))
        batch_op.drop_index(batch_op.f('ix_game_result_deck_id'))

    op.drop_table('game_result')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('deck')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_player_name'))

    op.drop_table('player')
    op.drop_table('game_session')
    op.drop_table('color_identity')
    # ### end Alembic commands ###
