"""empty message

Revision ID: 8470860ec0b9
Revises: ac85df05f662
Create Date: 2025-11-29 04:50:31.138387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8470860ec0b9'
down_revision = 'ac85df05f662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE user SET is_admin = false")
    
    # Make NOT NULL
    op.alter_column('user', 'is_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    op.drop_column('user', 'is_admin')

    # ### end Alembic commands ###
