"""add deck_colors table

Revision ID: 864430e5a06b
Revises: 8470860ec0b9
Create Date: 2025-11-29 06:47:27.476533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864430e5a06b'
down_revision = '8470860ec0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['color_identity.code'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id', 'color_id', name='uq_deck_color')
    )
    with op.batch_alter_table('deck_colors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deck_colors_color_id'), ['color_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deck_colors_deck_id'), ['deck_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_colors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deck_colors_deck_id'))
        batch_op.drop_index(batch_op.f('ix_deck_colors_color_id'))

    op.drop_table('deck_colors')
    # ### end Alembic commands ###
