"""empty message

Revision ID: ab6e5c4bef55
Revises: 30325487365f
Create Date: 2025-11-24 01:23:29.938307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6e5c4bef55'
down_revision = '30325487365f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_result', schema=None) as batch_op:
        batch_op.drop_column('gr_wincon')
        batch_op.drop_column('comments')

    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gs_wincon', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_column('comments')
        batch_op.drop_column('gs_wincon')

    with op.batch_alter_table('game_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('gr_wincon', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
