"""empty message

Revision ID: ac85df05f662
Revises: ab6e5c4bef55
Create Date: 2025-11-28 02:31:34.039710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac85df05f662'
down_revision = 'ab6e5c4bef55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('color_identity', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=5),
               existing_nullable=False)

    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.alter_column('color_identity_code',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.alter_column('color_identity_code',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)

    with op.batch_alter_table('color_identity', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)

    # ### end Alembic commands ###
